name: "Test"
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'releases/*'

permissions: 
  id-token: write
  contents: write

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
    - uses: ./
      with:
        filePath: "test"
        
